In [11]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from solution_utils import build_tables, get_users_text

In [12]:
data = pd.read_json('hw1_train.jsonl', lines=True)

# data = data.drop(columns='dialog_id')
data

,dialog_id,language,n_user_turns,turns,labels
0,d094012177e,en,7,"[{'role': 'user', 'text': 'it’s like: 1+1=2, b...","{'task_type': 'analysis', 'reaction': 'positiv..."
1,d306fbe61fe,en,8,"[{'role': 'user', 'text': 'Can you help me tra...","{'task_type': 'information_seeking', 'reaction..."
2,dd6905952c7,en,5,"[{'role': 'user', 'text': 'ask questions about...","{'task_type': 'creation', 'reaction': 'neutral..."
3,d767a675896,en,6,"[{'role': 'user', 'text': 'Calculate each prom...","{'task_type': 'information_seeking', 'reaction..."
4,d7a6280ce8e,en,8,"[{'role': 'user', 'text': 'mass spectrometer, ...","{'task_type': 'information_seeking', 'reaction..."
...,...,...,...,...,...
9995,d745e2d0b74,en,8,"[{'role': 'user', 'text': 'which countries off...",None
9996,d2248b50e1e,en,6,"[{'role': 'user', 'text': 'Medication safety, ...",None
9997,dba01d56b0d,en,10,"[{'role': 'user', 'text': 'Your instructions a...",None
9998,d07a2ffacb8,en,5,"[{'role': 'user', 'text': 'write a story for p...",None
9999,dbba647d849,en,10,"[{'role': 'user', 'text': 'prison, sentence or...",None

In [13]:
print(f'доля записей с labels {data['labels'].notna().mean()}')
data = data.drop(columns='labels')

доля записей с labels 0.3

ответы нейронки смотреть смысла нет, так как пользователь задаёт тему и ведет её, нейронка только поддакивает

In [14]:
dialogs, turn = build_tables(data.to_dict('records'))

user = dialogs.iloc[0, 2]

# for replica in user:
#     print(replica)

print (user[0])

dialogs

i

,language,n_user_turns,user_text,assistant_text,user_len,assistant_len,reaction,task_type
dialog_id,,,,,,,,
d094012177e,en,7,"it’s like: 1+1=2, but 1+1=2+1+1=? is undefined...",Introducing scientific terms from astrophysics...,8453,10492,None,None
d306fbe61fe,en,8,Can you help me train a small language model t...,Creating a small language model from scratch i...,1278,32255,None,None
dd6905952c7,en,5,ask questions about a fictional voice actor i ...,1. How did this fictional voice actor get into...,3326,11938,None,None
d767a675896,en,6,Calculate each prompt based off of data and sh...,"To calculate Species Richness, simply count th...",1115,9253,None,None
d7a6280ce8e,en,8,"mass spectrometer, the length of AC rod will i...",As an AI language model I don't have enough in...,374,7528,None,None
...,...,...,...,...,...,...,...,...
d745e2d0b74,en,8,which countries offer special programs to enco...,There are several countries that offer special...,433,11913,None,None
d2248b50e1e,en,6,"Medication safety, \n\nMedication administrati...",This documentation is important in ensuring co...,2776,5259,None,None
dba01d56b0d,en,10,Your instructions are: For the following quest...,"As an AI language model, I do not possess the ...",995,8526,None,None
d07a2ffacb8,en,5,write a story for primary students in less tha...,Holiday Shopping\n\nMrs. Miller is doing her h...,1490,4557,None,None
dbba647d849,en,10,"prison, sentence or prison, sintence?\n“prison...","The correct spelling is ""prison, sentence.""\nA...",892,4878,None,None

In [15]:
all_text = get_users_text(data.to_dict('records'), text_type='user')